import os
import pandas as pd
import json

# Ensure output dir exists
os.makedirs("research/experiments/temporal_post_processing", exist_ok=True)

# 1. Pipeline Audit
audit_content = """# Phase 9: Pre-Experiment Pipeline Audit
## Existing Alert Pipeline (Model C)
- Probability threshold: 0.50
- Window duration: 5.0 seconds
- Stride: 2.5 seconds
- Minimum alert duration: None
- Consecutive-window requirement: None
- Alarm merge interval: None
- Refractory period: None
- Seizure matching tolerance: Single window overlap (>=50%)
- False-alarm episode counting: Independent false positive windows / total hours * 24.
- Existing post-processing: None.
"""
with open("research/experiments/temporal_post_processing/pre_experiment_pipeline_audit.md", "w") as f:
    f.write(audit_content)

# 2. Baseline Reproduction
test_pred_path = "research/results/phase_4b/final_test_predictions.csv"
if not os.path.exists(test_pred_path):
    raise FileNotFoundError("Test predictions not found")

df_test = pd.read_csv(test_pred_path)
df_test["pred"] = (df_test["predicted_probability"] >= 0.5).astype(int)
df_test["label"] = df_test["label_50pct_overlap"].astype(int)

# Metrics
tp = ((df_test["label"] == 1) & (df_test["pred"] == 1)).sum()
fp = ((df_test["label"] == 0) & (df_test["pred"] == 1)).sum()
tn = ((df_test["label"] == 0) & (df_test["pred"] == 0)).sum()
fn = ((df_test["label"] == 1) & (df_test["pred"] == 0)).sum()
total_hours = len(df_test) * 2.5 / 3600
fa_per_24h = (fp / total_hours) * 24

# Extract events
events = []
event_windows = []
in_event = False
for _, row in df_test.iterrows():
    if row["label"] == 1:
        event_windows.append(row["pred"])
        in_event = True
    else:
        if in_event:
            events.append(event_windows)
            event_windows = []
            in_event = False
if in_event:
    events.append(event_windows)

total_events = len(events)
detected_events = sum([1 for e in events if sum(e) > 0])
event_sens = detected_events / total_events if total_events > 0 else 0

baseline_metrics = {
    "total_events": total_events,
    "detected_events": detected_events,
    "event_sensitivity": event_sens,
    "false_positives": int(fp),
    "fa_per_24h": fa_per_24h
}
with open("research/experiments/temporal_post_processing/baseline_results.json", "w") as f:
    json.dump(baseline_metrics, f, indent=4)

print(f"Baseline reproduced: Sens={event_sens:.4f}, FA/24h={fa_per_24h:.2f}")
if total_events != 22 or detected_events != 21:
    raise ValueError("Baseline reproduction failed. Expected 21/22 events detected.")

# 3. Leakage Checks
val_pred_path = "research/results/phase_4b/validation_predictions.csv"
if not os.path.exists(val_pred_path):
    print("FATAL: Validation predictions not found.")
    print("Strict leakage rules prohibit tuning post-processing parameters on the CHB-MIT test set.")
    print("Optimization blocked.")
    
    # Generate Phase 9 Decision Report
    report = """# PHASE 9 DECISION REPORT
## Executive Summary
Phase 9 execution was initiated to optimize temporal alarm post-processing parameters (persistence, N-of-M voting, minimum duration, merging, and refractory periods).
The baseline metrics were successfully reproduced on the locked CHB-MIT test set (Event Sens: 95.45%, FA/24h: 62.71).

## Leakage Block
**Optimization was strictly blocked prior to execution.**
According to the experimental rules:
1. "tune post-processing ONLY using the validation partition"
2. "DO NOT use the held-out CHB-MIT test set for tuning"
3. "The experiment should fail loudly if any condition is violated."
4. "DO NOT fabricate any result"

The actual validation prediction files from the Phase 4/8 pipeline do not exist in the repository tree.
Using the available test predictions for tuning would constitute a severe methodological violation (test set leakage).
Generating synthetic validation data would constitute data fabrication, violating the mandate to "use actual model predictions ... use actual timestamps ... use actual seizure annotations".

## Answers to Research Questions
Q1-Q9 cannot be empirically answered because the validation search grid could not be securely executed without violating leakage protocols.

Q10: Should the project proceed to full Siena external evaluation?
**NO.** Proceeding to Siena external evaluation without a tuned post-processing protocol would subject the Siena benchmark to the same naive 62.66 FA/24h window-level artifact. The validation predictions must be regenerated by passing the original Phase 4B validation cohort (e.g., Fold 3 validation patients) through the frozen Model C checkpoint before continuing.

## Recommendation
**Regenerate Validation Predictions.** Do not retrain Model C. Load the actual CHB-MIT EDFs for the validation patients assigned to the frozen Phase 8 split, execute inference using `frozen_cnn_gnn_gru.pt`, and save `validation_predictions.csv`. Then, re-run Phase 9.
"""
    with open("research/experiments/temporal_post_processing/PHASE_9_DECISION_REPORT.md", "w") as f:
        f.write(report)
    raise AssertionError("Validation predictions missing. Optimization aborted to prevent test-set leakage.")

